services:
  database:
    image: mongo:latest
    container_name: assis_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: assis_db
    volumes:
      - ./scripts/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - mongo_data:/data/db
    networks:
      - falatexto-network

  api:
    build: .
    container_name: assis_api
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB_NAME: assis_db
    networks:
      - falatexto-network

volumes:
  mongo_data:

networks:
  falatexto-network:
    driver: bridge